### ISSUE TITLE
What is license?

### ISSUE THREAD

**Issue by tomykaira** [Yalir/Synthese4A#1]
We are thinking of including a part of this project in our application.
According to https://github.com/Yalir/Synthese4A/blob/master/openssl_aes.c#L5, it seems like public domain, but I am not sure about other code.
Let me know about license.
Thanks in advance.

**Comment by Ceylo** [comment]
The file you're referring to is indeed in the public domain. The biggest part of the sources is from pidgin and its libpurple project which are under GPL. Most of the personal work is in pidgin-2.10.7/libpurple/protocols/jabber/jbl, which is also under GPL. This implies you can use it as you want as long as your respect GPL license terms. I hope this helps :)

**Comment by tomykaira** [comment]
Thanks a lot, and sorry for late reply!
